### PR TITLE
[CLOUD-2081] remove hawular agent artifact

### PR DESCRIPTION
**Pull request by pgier**
The hawkular agent artifact is now included in the cct os-hawkular-java module

https://issues.jboss.org/browse/CLOUD-2081

Signed-off-by: Paul Gier <pgier@redhat.com>

### CODE REVIEW

**Comment by psiroky** [comment]
@pgier I don't see the `os-hawkular-java` module being used. Should we add it?

**Comment by pgier** [comment]
@psiroky I believe it's in all four of the image configs.  For example: https://github.com/jboss-container-images/jboss-bpmsuite-7-openshift-image/blob/bpmsuite70-dev/businesscentral/image.yaml#L287
And the hawkular-agent jar seems to have installed correctly in my test image, AFAICT.

**Comment by psiroky** [comment]
@pgier huh, sorry, of course it's there. Not sure what I was looking at before.

**Review by psiroky — APPROVED** [review]

**Comment by spolti** [comment]
@ryanzhang f.y.i.

**Comment by ryanzhang** [comment]
@spolti Should we do further developement in new repo rhba-7-openshift-image to match the new product name?

**Review by spolti — APPROVED** [review]
LGTM, if not remove image build will fail.

**Pull request merged**
