### PR TITLE
Prepare for 7.0.0.CR01 tag

### PR DESCRIPTION
**Pull request by psiroky**
After merging this, we need to create a new tag and change the version back to 1.0.

### CODE REVIEW

**Comment by goldmann** [comment]
I'm not sure I like it, again. You should just build `1.0` images, without adding any CR tags. CR is targeting a GA release. If there are no issues with the CR - this build could be used as GA. With tags like this you need to rebuild the image again. And test it again.

Tagging should be done outside of the image;

1. post-processing of tags after building the image
2. Tagging the source code repository.

Generally speaking we don't specify any versions for CR/development builds at all. We do it for public releases. And releases can be one of: Alpha, Beta, GA.

**Comment by ryanzhang** [comment]
Yep, understood. 
For LA release, we need to package the sources somehow after the image built successfully.
This might be the difference requirement as other releases. 
So I think that we might need to tag it somehow to make sure that we can track the sources of particular internal release.  eg if QE reports a bug, it should be able to reproduce by identifying the source.

**Comment by ryanzhang** [comment]
I think this PR is not required  since there is no code change needed. The open question is if we should tag the source for CR1.

**Comment by goldmann** [comment]
Sure, that's not in contradiction with what I said - this whole repository would be tagged, but I would not add the tag to image descriptors at all.

**Comment by psiroky** [comment]
Sounds good. I was merely following what was previously done by @errantepiphany for the tag [bpmsuite70-1.0.Beta01](https://github.com/jboss-container-images/jboss-bpmsuite-7-openshift-image/tree/bpmsuite70-1.0.Beta01). Closing as this is not needed.

**Pull request closed without merging**
