### PR TITLE
Add missing os-eap70-openshift CCT scripts to BC and kie-server

### PR DESCRIPTION
**Pull request by rbarriuso**

### CODE REVIEW

**Comment by rbarriuso** [comment]
See https://github.com/jboss-container-images/jboss-bpmsuite-7-openshift-image/pull/6#discussion_r128765625

**Comment by psiroky** [comment]
@errantepiphany could you please merge this? The current image as is does not work without this change.

**Comment by errantepiphany** [comment]
@psiroky I don't have permissions to. @goldmann , @dbecvarik : Can this please be merged?

**Comment by goldmann** [comment]
Merged!

**Comment by errantepiphany** [comment]
Thanks!

**Pull request merged**
